import { InMemoryCache } from 'apollo-cache-inmemory'

// generated by Fragment Matcher plugin
import generatedIntrospection from '@/apollo/fragment-types'

const cache = new InMemoryCache({
  possibleTypes: generatedIntrospection.possibleTypes,
})

export default (context) => {
  return {
    httpEndpoint: context.$config.apiUrl,
    cache,
    ssr: true,
    persisting: true,
  }
}
